name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project (if exists)
        run: vercel pull --yes --environment=production --token=${{ secrets.VercelToken }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          # Deploy with alias and capture the full output
          DEPLOY_OUTPUT=$(vercel deploy --prod --token=${{ secrets.VercelToken }} --yes --alias aneshain.vercel.app)
          echo "$DEPLOY_OUTPUT" # Log the full Vercel output for debugging

          # Extract the unique Vercel deployment URL (e.g., Production: https://...vercel.app)
          # Using \K to discard 'Production: ' and a lookahead for ' [Xs]' or end of line
          UNIQUE_DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -oP 'Production: \Khttps://[^\s]+(?=\s\[\d+s\]$|$)' || echo "")
          
          # The desired alias URL (Vercel should assign this if available)
          ALIAS_URL="https://aneshain.vercel.app"

          echo "unique_url=$UNIQUE_DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "alias_url=$ALIAS_URL" >> $GITHUB_OUTPUT
          echo "🚀 Deployment URL (Unique Vercel Hash): $UNIQUE_DEPLOY_URL"
          echo "✨ Deployment URL (Alias Requested): $ALIAS_URL"

      - name: Log Deployment URLs
        run: |
          echo "Live at (Unique): ${{ steps.deploy.outputs.unique_url }}"
          echo "Live at (Alias): ${{ steps.deploy.outputs.alias_url }}"