name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project (if exists)
        run: vercel pull --yes --environment=production --token=${{ secrets.VercelToken }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          DEPLOY_URL=$(vercel deploy --prod --token=${{ secrets.VercelToken }} --yes | grep -o 'https://[^\s]*')
          echo "::set-output name=url::$DEPLOY_URL"
          echo "🚀 Deployment URL: $DEPLOY_URL"

      - name: Log Deployment URL
        run: echo "Live at ${{ steps.deploy.outputs.url }}"